const champs = {
  garen: {
    version: "13.14.1",
    id: "Garen",
    key: "86",
    name: "Garen",
    title: "The Might of Demacia",
    blurb:
      "A proud and noble warrior, Garen fights as one of the Dauntless Vanguard. He is popular among his fellows, and respected well enough by his enemies—not least as a scion of the prestigious Crownguard family, entrusted with defending Demacia and its...",
    info: {
      attack: 7,
      defense: 7,
      magic: 1,
      difficulty: 5,
    },
    image: {
      full: "Garen.png",
      sprite: "champion1.png",
      group: "champion",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ["Fighter", "Tank"],
    partype: "None",
    stats: {
      hp: 690,
      hpperlevel: 98,
      mp: 0,
      mpperlevel: 0,
      movespeed: 340,
      armor: 38,
      armorperlevel: 4.2,
      spellblock: 32,
      spellblockperlevel: 1.55,
      attackrange: 175,
      hpregen: 8,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 69,
      attackdamageperlevel: 4.5,
      attackspeedperlevel: 3.65,
      attackspeed: 0.625,
    },
  },
  ahri: {
    version: "13.14.1",
    id: "Ahri",
    key: "103",
    name: "Ahri",
    title: "the Nine-Tailed Fox",
    blurb:
      "Innately connected to the magic of the spirit realm, Ahri is a fox-like vastaya who can manipulate her prey's emotions and consume their essence—receiving flashes of their memory and insight from each soul she consumes. Once a powerful yet wayward...",
    info: {
      attack: 3,
      defense: 4,
      magic: 8,
      difficulty: 5,
    },
    image: {
      full: "Ahri.png",
      sprite: "champion0.png",
      group: "champion",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ["Mage", "Assassin"],
    partype: "Mana",
    stats: {
      hp: 590,
      hpperlevel: 96,
      mp: 418,
      mpperlevel: 25,
      movespeed: 330,
      armor: 21,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 2.5,
      hpregenperlevel: 0.6,
      mpregen: 8,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.668,
    },
  },
  akali: {
    version: "13.14.1",
    id: "Akali",
    key: "84",
    name: "Akali",
    title: "the Rogue Assassin",
    blurb:
      "Abandoning the Kinkou Order and her title of the Fist of Shadow, Akali now strikes alone, ready to be the deadly weapon her people need. Though she holds onto all she learned from her master Shen, she has pledged to defend Ionia from its enemies, one...",
    info: {
      attack: 5,
      defense: 3,
      magic: 8,
      difficulty: 7,
    },
    image: {
      full: "Akali.png",
      sprite: "champion0.png",
      group: "champion",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ["Assassin"],
    partype: "Energy",
    stats: {
      hp: 570,
      hpperlevel: 119,
      mp: 200,
      mpperlevel: 0,
      movespeed: 345,
      armor: 23,
      armorperlevel: 4.7,
      spellblock: 37,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 9,
      hpregenperlevel: 0.9,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 3.3,
      attackspeedperlevel: 3.2,
      attackspeed: 0.625,
    },
  },
  ashe: {
    version: "13.14.1",
    id: "Ashe",
    key: "22",
    name: "Ashe",
    title: "the Frost Archer",
    blurb:
      "Iceborn warmother of the Avarosan tribe, Ashe commands the most populous horde in the north. Stoic, intelligent, and idealistic, yet uncomfortable with her role as leader, she taps into the ancestral magics of her lineage to wield a bow of True Ice...",
    info: {
      attack: 7,
      defense: 3,
      magic: 2,
      difficulty: 4,
    },
    image: {
      full: "Ashe.png",
      sprite: "champion0.png",
      group: "champion",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ["Marksman", "Support"],
    partype: "Mana",
    stats: {
      hp: 640,
      hpperlevel: 101,
      mp: 280,
      mpperlevel: 35,
      movespeed: 325,
      armor: 26,
      armorperlevel: 4.6,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 600,
      hpregen: 3.5,
      hpregenperlevel: 0.55,
      mpregen: 7,
      mpregenperlevel: 0.65,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 2.95,
      attackspeedperlevel: 3.33,
      attackspeed: 0.658,
    },
  },
  ezreal: {
    version: "13.14.1",
    id: "Ezreal",
    key: "81",
    name: "Ezreal",
    title: "the Prodigal Explorer",
    blurb:
      "A dashing adventurer, unknowingly gifted in the magical arts, Ezreal raids long-lost catacombs, tangles with ancient curses, and overcomes seemingly impossible odds with ease. His courage and bravado knowing no bounds, he prefers to improvise his way...",
    info: {
      attack: 7,
      defense: 2,
      magic: 6,
      difficulty: 7,
    },
    image: {
      full: "Ezreal.png",
      sprite: "champion0.png",
      group: "champion",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
    tags: ["Marksman", "Mage"],
    partype: "Mana",
    stats: {
      hp: 600,
      hpperlevel: 102,
      mp: 375,
      mpperlevel: 70,
      movespeed: 325,
      armor: 24,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 550,
      hpregen: 4,
      hpregenperlevel: 0.65,
      mpregen: 8.5,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 62,
      attackdamageperlevel: 2.5,
      attackspeedperlevel: 2.5,
      attackspeed: 0.625,
    },
  },
  hecarim: {
    version: "13.14.1",
    id: "Hecarim",
    key: "120",
    name: "Hecarim",
    title: "the Shadow of War",
    blurb:
      "Hecarim is a spectral fusion of man and beast, cursed to ride down the souls of the living for all eternity. When the Blessed Isles fell into shadow, this proud knight was obliterated by the destructive energies of the Ruination, along with all his...",
    info: {
      attack: 8,
      defense: 6,
      magic: 4,
      difficulty: 6,
    },
    image: {
      full: "Hecarim.png",
      sprite: "champion1.png",
      group: "champion",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
    tags: ["Fighter", "Tank"],
    partype: "Mana",
    stats: {
      hp: 625,
      hpperlevel: 99,
      mp: 277,
      mpperlevel: 60,
      movespeed: 345,
      armor: 32,
      armorperlevel: 5.45,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 175,
      hpregen: 7,
      hpregenperlevel: 0.75,
      mpregen: 6.5,
      mpregenperlevel: 0.6,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 3.2,
      attackspeedperlevel: 2.5,
      attackspeed: 0.67,
    },
  },
  janna: {
    version: "13.14.1",
    id: "Janna",
    key: "40",
    name: "Janna",
    title: "the Storm's Fury",
    blurb:
      "Armed with the power of Runeterra's gales, Janna is a mysterious, elemental wind spirit who protects the dispossessed of Zaun. Some believe she was brought into existence by the pleas of Runeterra's sailors who prayed for fair winds as they navigated...",
    info: {
      attack: 3,
      defense: 5,
      magic: 7,
      difficulty: 7,
    },
    image: {
      full: "Janna.png",
      sprite: "champion1.png",
      group: "champion",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
    tags: ["Support", "Mage"],
    partype: "Mana",
    stats: {
      hp: 570,
      hpperlevel: 84,
      mp: 350,
      mpperlevel: 64,
      movespeed: 325,
      armor: 28,
      armorperlevel: 5,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 500,
      hpregen: 5.5,
      hpregenperlevel: 0.55,
      mpregen: 11.5,
      mpregenperlevel: 0.4,
      crit: 0,
      critperlevel: 0,
      attackdamage: 52,
      attackdamageperlevel: 3,
      attackspeedperlevel: 3,
      attackspeed: 0.625,
    },
  },
  vi: {
    version: "13.14.1",
    id: "Vi",
    key: "254",
    name: "Vi",
    title: "the Piltover Enforcer",
    blurb:
      "Once a criminal from the mean streets of Zaun, Vi is a hotheaded, impulsive, and fearsome woman with only a very loose respect for authority figures. Growing up all but alone, Vi developed finely honed survival instincts as well as a wickedly abrasive...",
    info: {
      attack: 8,
      defense: 5,
      magic: 3,
      difficulty: 4,
    },
    image: {
      full: "Vi.png",
      sprite: "champion4.png",
      group: "champion",
      x: 192,
      y: 96,
      w: 48,
      h: 48,
    },
    tags: ["Fighter", "Assassin"],
    partype: "Mana",
    stats: {
      hp: 655,
      hpperlevel: 99,
      mp: 295,
      mpperlevel: 65,
      movespeed: 340,
      armor: 30,
      armorperlevel: 4.7,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 10,
      hpregenperlevel: 1,
      mpregen: 8,
      mpregenperlevel: 0.65,
      crit: 0,
      critperlevel: 0,
      attackdamage: 63,
      attackdamageperlevel: 3,
      attackspeedperlevel: 2,
      attackspeed: 0.644,
    },
  },
  jinx: {
    version: "13.14.1",
    id: "Jinx",
    key: "222",
    name: "Jinx",
    title: "the Loose Cannon",
    blurb:
      "A manic and impulsive criminal from Zaun, Jinx lives to wreak havoc without care for the consequences. With an arsenal of deadly weapons, she unleashes the loudest blasts and brightest explosions to leave a trail of mayhem and panic in her wake. Jinx...",
    info: {
      attack: 9,
      defense: 2,
      magic: 4,
      difficulty: 6,
    },
    image: {
      full: "Jinx.png",
      sprite: "champion1.png",
      group: "champion",
      x: 0,
      y: 96,
      w: 48,
      h: 48,
    },
    tags: ["Marksman"],
    partype: "Mana",
    stats: {
      hp: 630,
      hpperlevel: 100,
      mp: 260,
      mpperlevel: 50,
      movespeed: 325,
      armor: 26,
      armorperlevel: 4.7,
      spellblock: 30,
      spellblockperlevel: 1.3,
      attackrange: 525,
      hpregen: 3.75,
      hpregenperlevel: 0.5,
      mpregen: 6.7,
      mpregenperlevel: 1,
      crit: 0,
      critperlevel: 0,
      attackdamage: 59,
      attackdamageperlevel: 3.15,
      attackspeedperlevel: 1,
      attackspeed: 0.625,
    },
  },
  leesin: {
    version: "13.14.1",
    id: "LeeSin",
    key: "64",
    name: "Lee Sin",
    title: "the Blind Monk",
    blurb:
      "A master of Ionia's ancient martial arts, Lee Sin is a principled fighter who channels the essence of the dragon spirit to face any challenge. Though he lost his sight many years ago, the warrior-monk has devoted his life to protecting his homeland...",
    info: {
      attack: 8,
      defense: 5,
      magic: 3,
      difficulty: 6,
    },
    image: {
      full: "LeeSin.png",
      sprite: "champion2.png",
      group: "champion",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ["Fighter", "Assassin"],
    partype: "Energy",
    stats: {
      hp: 645,
      hpperlevel: 105,
      mp: 200,
      mpperlevel: 0,
      movespeed: 345,
      armor: 34,
      armorperlevel: 4.9,
      spellblock: 32,
      spellblockperlevel: 2.05,
      attackrange: 125,
      hpregen: 7.5,
      hpregenperlevel: 0.7,
      mpregen: 50,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 66,
      attackdamageperlevel: 3.7,
      attackspeedperlevel: 3,
      attackspeed: 0.651,
    },
  },
};

// Esto es un ejemplo de la respuesta que voy a obtener de la API de RiotGames,
// si tan solo supiera usarla 💪 (inserten meme de padrinos magicos https://www.youtube.com/watch?v=hBDm3NPwAIA&ab_channel=LeandroRamos)
